[package]
name = "bikeshed-demo"
version = "0.1.0"
authors = ["whichxjy <whichxjy@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
regex = "1"
titlecase = "1"
chrono = "0.4"
lazy_static = "1.4.0"
maplit = "1.0.2"
kuchiki = "0.8.0"